### ISSUE TITLE
Arguments in assemble_reads.py

### ISSUE THREAD

**Issue by SergioB1983** [AntonelliLab/seqcap_processor#10]
Hi, 

I have problems running the script `secapr assemble_reads`. This is the error that the system shows me:

`Processing sample P02_WB06
Traceback (most recent call last):
  File "/home/sergiod/miniconda2/envs/secapr_env/bin/secapr", line 11, in <module>
    sys.exit(main())
  File "/home/sergiod/miniconda2/envs/secapr_env/lib/python2.7/site-packages/secapr/__main__.py", line 52, in main
    args.func(args)
  File "/home/sergiod/miniconda2/envs/secapr_env/lib/python2.7/site-packages/secapr/assemble_reads.py", line 134, in main
    assembly_trinity(forward,backward,sample_output_folder,sample_id,cores,min_length)
TypeError: assembly_trinity() takes exactly 7 arguments (6 given)
`
I install the repositories via conda, install the lastest version of script and tried with a recent version of Trinity (2.6), but the error persists. Also the input data was created using the `secapr clean_reads` script

It is a problem in my installation, or is a problem in the script?

Thanks in advance!

**Comment by tobiashofmann88** [comment]
Hey Sergio,
Thanks for the helpful bugreport.
It was indeed a problem in the script.
I fixed the issue and submitted the new secapr version (1.1.11) to the conda server. Once the conda staff approved my changes the new version will be available through conda by typing `conda update secapr`
Best,
Tobi

**Comment by tobiashofmann88** [comment]
the update with bugfix is available now as version 1.1.12
