### ISSUE TITLE
phase_alleles requires --reference flag parameter

### ISSUE THREAD

**Issue by btsinn** [AntonelliLab/seqcap_processor#14]
Hello,

I am attempting to run the phase_alleles function and I notice that the version of secapr that I have installed (v 1.1.15; Linux via Conda) asks for a --reference flag:

usage: secapr phase_alleles [-h] --input INPUT --output OUTPUT
                            [--min_coverage MIN_COVERAGE] --reference
                            REFERENCE

The --reference flag is not listed in the documentation as a requirement of phase_alleles, and I wonder what the user should point the flag to, especially in the case of using the alignment-consensus option during reference_assembly. Thanks so much!

**Comment by tobiashofmann88** [comment]
Yes, I need to update the documentation, thanks for mentioning!
If you use the help function (secapr phase_alleles -h) SECAPR will explain what needs to be provided. In this case you need to provide the reference fasta that was used for read mapping.
Best,
Tobi


------------------------------------------------------
Tobias Andermann (Hofmann)
PhD student
Biological and Environmental Sciences, University of Gothenburg
The Antonelli Lab <http://antonelli-lab.net/> | Gothenburg Global Biodiversity Centre <http://ggbc.gu.se/>
Carl Skottsbergs gata 22 B <https://goo.gl/maps/mwGPq3HNzAN2>, 413 19 Göteborg
tobias.andermann@bioenv.gu.se <mailto:tobias.andermann@bioenv.gu.se>
+46 76 090 1106
github.com/tobiashofmann88 <https://github.com/tobiashofmann88>
Google Scholar profile <https://scholar.google.se/citations?user=soeWAQwAAAAJ&hl=en&oi=ao>
------------------------------------------------------

**Comment by btsinn** [comment]
Thanks for your reply, Tobi. 

Isn't it the case that the instructions provided with the -h flag only refer to a the file location of the reference used for reference-based assembly, and not the alignment-consensus reference option?

**Comment by tobiashofmann88** [comment]
If you choose alignment-consensus in the reference_assembly function, the program will produce a reference fasta file (called “joined_fasta_library.fasta”, found in the reference_seqs folder in the output directory). That’s the file you have to provide for the phase_alleles function.
Best,
Tobi
 
------------------------------------------------------
Tobias Andermann (Hofmann)
PhD student
Biological and Environmental Sciences, University of Gothenburg
The Antonelli Lab <http://antonelli-lab.net/> | Gothenburg Global Biodiversity Centre <http://ggbc.gu.se/>
Carl Skottsbergs gata 22 B <https://goo.gl/maps/mwGPq3HNzAN2>, 413 19 Göteborg
tobias.andermann@bioenv.gu.se <mailto:tobias.andermann@bioenv.gu.se>
+46 76 090 1106
github.com/tobiashofmann88 <https://github.com/tobiashofmann88>
Google Scholar profile <https://scholar.google.se/citations?user=soeWAQwAAAAJ&hl=en&oi=ao>
------------------------------------------------------

**Comment by btsinn** [comment]
Thanks, Tobi!
