### ISSUE TITLE
Python 2.7 is end-of-life

### ISSUE THREAD

**Issue by marcelm** [AntonelliLab/seqcap_processor#19]
I just saw that Bioconda is going to drop support for Python 2.7, see https://github.com/bioconda/bioconda-recipes/issues/19549, as [Python 2.7 has reached its end of life](https://pyfound.blogspot.com/2019/12/python-2-sunset.html). To keep secapr available on Bioconda, the best way forward would be to convert the code this project to Python 3.

*Edit:* linked to wrong issue

**Comment by tobiashofmann88** [comment]
just released a new Python 3 version of the program
