### ISSUE TITLE
"Average_cov_per_locus" file missing, causing error in plotting matrices of selected loci?

### ISSUE THREAD

**Issue by wtesto** [AntonelliLab/seqcap_processor#21]
Hey Tobi — 

I  have been having some difficulty generating plots with locus representation and read coverage from a selected set of loci.
I figured that I might be able to do it with plot_sequence_yield by modifying it from the earlier examples, and tried this:
`secapr plot_sequence_yield --extracted_contigs processed/target_contigs/ --alignments processed/alignments/contig_alignments/ --read_cov processed/selected_loci --coverage_norm 10 --output processed/plots`
but that did not seem to work — it threw an error that said no such file or directory `../../selected_loci/average_cov_per_locus.txt`

I checked the /selected_loci directory and I see that there is a file instead that is called “average_read_coverage_across_selected_loci_per_sample.txt” and am wondering if this is the same file but just gets written with a new name now and doesn’t match what is being called in plot_sequence_yield?

**Comment by tobiashofmann88** [comment]
Thanks for reporting the bug!
I have made a few changes to both the `locus_selection` and the `plot_sequences` function and it should work fine now. I will soon release a new conda verison with the fixes, but you can use the github development version in the meanwhile (see installation instructions at the end of the readme) to run the fixed function already now. You will need to rerun `locus_selection` as well or manually rename the `overview_selected_loci.txt` file to `average_cov_per_locus.txt`.
Let me know in case you run into more issues.
