### ISSUE TITLE
Reconstructing phased sequences for homozygous individuals

### ISSUE THREAD

**Issue by Anh-Thu-Weber** [AntonelliLab/seqcap_processor#9]
Hi,

I'm using your pipeline to reconstruct allele sequences for a particular locus, and I realised that the phasing step does not work for homozygous individuals even though the assembly step worked 

Could you help me solve this?

Thanks in advance,

Alexandra

**Comment by tobiashofmann88** [comment]
Let me know if this is still an issue, I think I fixed this a while ago, but am just now gettign to clean up the raised issues here on github
